sudo: false
language: scala
scala:
  - 2.11.7
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database pollzone;' -U postgres
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
env:
  global:
    - secure: Fkpk05zxki9YpgrP9maz24u5sYY9qeUByr5sXBKWatDB7l+RHAmh7NdreAB7JDyXYHI+owk/fE+y4rAEeT3u4ZuPhZk0bVQXLxCfqGdPrtaJXVCjwcg1DRbogWr5ZbwOohlX3eJwkucT8gKFjoPSGRy8o0XMaup0id0jrlXNnUA1J/Ocbct7WIqZ2TrXwKbzaUU0IlGr8NFCc9yI6Ch6fZV1+DEUxUQ05ImTx9+qXJ+7QjnESTKJ/T9lgMa4sidw5wjIyuj9pyYc0JwcLEHAVv+sGQIXBqTRt3x7c4Zs8gFzN3TwuwhcYaIvHByCmHkpqwHRn+Hb770XOQGA/sZR3+tBfJHzsgrd1CgeKrr9uVMsBAQvocDsIG0IY/vu4WVRXmPsDsoEmh90g3vYYxOTKwfprHG02+2lI+VZkNryFriQcFtK2znTl5+0GpAchCEZ8E26H0MVsFKqRRK93w9zl7lo7CGH/YNIg76qiDmwTuPLcwn9Yi6PL53ICGGRdzL9xWIpXfGsIF2ygm2kPBj4Ncmp6mgf2OvivJPoExvFK4aS25qpMSfPDwgCedV4U3HUy1CaSGsVXr63KOXJ4fKDngI5ukojaPa7SEIJiE2QbsnkFeuHiqnenLIlYhA5wBvzTqjt6ljJaMgdEFuSzkcWkZx4u27MgLUnAnUaDTSCa/M=
    - secure: XurdlRkIjBUFM3kPu+M/lrK/NsQLeHBTr+JIMXRAT2E57qyEqeTZKZc+FsPJGL7VT8okHHfLWN2DvnsDgtxCz4iVrchjPhT+7YfSSgbbCPBN4EkHCXFMCouB4UDu/DWiGshQgi9b1oeAfyIMNvxQlTBm/ci7MhSppqySfkJkzck/58GuYIias9yQRZYIcCSrUbCkBl/c+EHMBVmfl6rqnVxIQsrH9/TcK7r6RivWO4hiFotQdctkzHOpygtFQbPToutpIIjynTMVtIHqCR279kNZrjBweZT5TbSOJU/EtxLpTxJzCXqJ5OPPFpxYXHvxVmswlzCP2OJ4ndHUsWRbCNnpPC93Xxwmg65QOUlxCPOPP2IDloRMD5nrYD60HpEKDfH/1/9MmRZF7k9c2XkMHh/jGDgOplvQIwnH/sdISFP5/aQQabtt8geFbmsvHR8d0Oq2ch6vZQ0tBEbMPWodXQfT+5Pta7M4DPKTVaYXjIHvDf2/qP1Wp+TgxEZSVOxzBRefjRN9DwtSpNlf0o4+LXRpU52sI7Eo76iKq9NM+lAV+OOzZQau6kJbF1yxxF2NV/2Sc7ao+PHA/B56fr56IrKHQFX/HH92GSzb67Nb7VrNMlOFwGYU7WlNreaeitStH/ToCOIkUoTWGd/P6+4shdVl/6RETe6PVIa6/ydYm+M=
    - DB_PASSWORD: ''
    - DB_USERNAME: postgres
jdk:
- oraclejdk8
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
notifications:
  slack:
    secure: T66NTaZXlSedNhirrFQ11NOPjubOolJ4IIYgBxHd5tV0MIwv2WXc04p0+x906PGO1dFk+dijf9j3jikIxmKVxHhP60epuMC3spfp6DaE/Gz5Uhp1VfSCtvtCDN9+w8U2b0UUrqWgw9ggS2/lQ/sKx847bnihAeKHy71F3zbzaD4=
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
